### ISSUE TITLE
Thêm setting và chỉnh sửa cấu trúc code

### ISSUE THREAD

**Issue by bit-thuynt** [duoctvd/duoctv-trainning#26]
@duoctvd Chị note mấy cái cần chỉnh sửa vào đây khi nào tiện thì em làm nha.

1. Cấu trúc lại source với folder src
- pages => src/pages
- components => src/components

2. Thêm check vào eslint
Thay đổi `.eslintrc` thành `.eslintrc.js` rồi thêm setting sau vào
```
module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
  ],
  ignorePatterns: ["public/service-worker.js"],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2020,
    sourceType: "module",
  },
  plugins: ["react", "@typescript-eslint", "react-hooks"],
  rules: {
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/ban-ts-ignore": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-explicit-any": "off",
    eqeqeq: ["error", "always", { null: "ignore" }],
    "no-console": "error",
    "no-debugger": "error",
    "react-hooks/exhaustive-deps": "warn",
    "react-hooks/rules-of-hooks": "error",
    "react/jsx-no-bind": [
      "error",
      {
        allowArrowFunctions: true,
        allowBind: false,
        allowFunctions: false,
        ignoreDOMComponents: false,
        ignoreRefs: false,
      },
    ],
    "react/prop-types": "off",
    "react/react-in-jsx-scope": "off",
    "sort-keys": [
      "error",
      "asc",
      { caseSensitive: true, minKeys: 2, natural: false },
    ],
  },
  settings: {
    react: {
      version: "detect",
    },
  },
};
```
3. Thêm lệnh vào package.json
```
  "scripts": {
    "dev": "next dev -p 2311",
    "build": "next build",
    "start": "next start",
    "eslint": "eslint pages --ext .ts,.tsx,.js,.jsx --ignore-path ./.gitignore . --max-warnings=0",
    "eslint:fix": "yarn eslint --fix",
    "prettier": "prettier --write \"{,pages/**/,components/**}*.{js,jsx,ts,tsx,json,yaml,md}\""
  },
```

**Comment by duoctvd** [comment]
## What I have done
- Cấut trúc lại folder theo hướng dẫn và thêm cofig: DONE
- giải quyết vấn đề về: https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration : DONE

Hiện tại thì trên test sever mọi thứ hoạt động bình thường
https://duoctv-trainning-fhgukj8wy-duoctvd.vercel.app/admin/news/list
https://duoctv-trainning-fhgukj8wy-duoctvd.vercel.app/admin/news/form/LV4RoWAcAXHvAtvc4SQU
https://duoctv-trainning-fhgukj8wy-duoctvd.vercel.app/


Em sẽ tiếp tục 2 vụ dưới này
- pagination
- image upload

**Comment by bit-thuynt** [comment]
@duoctvd 
bỏ mấy cái folder `models`, `firestore` vào `src` lun nha em.
Sau này có thêm folder nào mới thì cũng bỏ vào `src` lun, chỉ những cái như `public` hoặc `locale` thì mới ko cho vào `src`

**Comment by duoctvd** [comment]
> @duoctvd
> bỏ mấy cái folder `models`, `firestore` vào `src` lun nha em.
> Sau này có thêm folder nào mới thì cũng bỏ vào `src` lun, chỉ những cái như `public` hoặc `locale` thì mới ko cho vào `src`

@bit-thuynt ah dạ, em sẽ thêm nó ở pagination task

**Comment by bit-thuynt** [comment]
@duoctvd Khi em làm xong issue nào đó thì em `Close` nó lun nha
